apiVersion: v1
kind: PersistentVolume
metadata:
  name: 2tier-pv2
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/DATA2/2tier-storage/pv02"

