apiVersion: v1
kind: Service
metadata:
  namespace: 2tier-ns
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress

