apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem  
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions: 
  - hard 
  nfs: 
    path: /DATA1
    server: 192.168.56.101
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: mynode-nfs-pod
spec:
  containers:
  - name: mynode
    image: dbgurum/mynode:1.0
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: testpath
      mountPath: /mount1
  volumes:
  - name : testpath
    persistentVolumeClaim:
      claimName: pvc-nfs

