apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sa-test-deploy
  name: sa-test-deploy
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-test-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sa-test-deploy
    spec:
      serviceAccountName: dev-sa
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
