apiVersion: v1
kind: Pod
metadata:
  name: client-app-pod
  labels:
    run: client-app
spec:
  containers:
  - name: myapp
    image: nginx:1.25.3
    volumeMounts:
    - name: html-app
      mountPath: /usr/share/nginx/html
  - name: sidecar
    image: curlimages/curl:8.5.0
    volumeMounts:
    - name: html-app
      mountPath: /html-log
    args: ["/bin/sh", "-c", "curl 10.109.131.34:8080/hostname > /html-log/index.html; sleep 3600;"]
  volumes:
  - name: html-app
    emptyDir: {}
