apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mynode-pod2
  name: mynode-svc2
spec:
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 8000
  selector:
    run: mynode-pod2
  type: NodePort
status:
  loadBalancer: {}
