apiVersion: v1
kind: Pod
metadata:
  name: myweb1
  labels:
     app: myweb
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: myweb2 
  labels:
     app: myweb
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
spec:
  selector:
    app: myweb
  ports:
  - port: 9000
    targetPort: 8080
    nodePort: 30090
  type: NodePort

