apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: c1
    image: dbgurum/k8s-lab:p8000
    ports:
    - containerPort: 8000
  - name: c2
    image: dbgurum/k8s-lab:p8080
    ports:
    - containerPort: 8080
