apiVersion: v1
kind: Pod
metadata:
  name: myweb-pod
  labels:
    app: myweb
spec:
  containers:
  - name: web-source
    image: alpine
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: source-volume
      mountPath: /source
  - name: webserver
    image: nginx:1.25.3-alpine
    volumeMounts:
    - name: source-volume
      mountPath: /usr/share/nginx/html/
  volumes:
    - name: source-volume
      emptyDir: {}
