apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mymotto
  name: mymotto
spec:
  containers:
  - image: dbgurum/mymotto:1.0
    name: mymotto
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
