apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mymotto
  name: mymotto-svc
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 80
  selector:
    run: mymotto
  type: NodePort
status:
  loadBalancer: {}
