apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cm-volume-pod
  name: cm-volume-pod
spec:
  containers:
  - image: nginx:1.25.3-alpine
    name: cm-volume-pod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/config
  volumes:
  - name: cm-volume
    configMap:
      name: k8s-env

