apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-pod
  labels:
    app: flaskapp
spec:
  containers:
  - image: nginx:1.25.3-alpine
    name: proxy-container
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx
    ports:
    - containerPort: 80
      protocol: TCP
  - image: dbgurum/py_flask:2.0
    name: flaskapp-container
    ports:
    - containerPort: 9000
      protocol: TCP
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: nginx-conf

