apiVersion: v1
kind: Pod
metadata:
  name: myweb-rq2
  namespace: dev-ns
spec:
  containers:
  - image: nginx
    name: myweb-rq1
    resources:
      requests:
        cpu: "50m"
        memory: 0.8Gi
      limits:
        cpu: "100m"
        memory: 0.8Gi

