apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-2
  namespace: dev-ns
spec:
  hard:
    requests.cpu: "100m"
    limits.cpu: "200m"
    requests.memory: 1Gi
    limits.memory: 1Gi
    configmaps: 5
    services: 5
    services.nodeports: 2
    pods: 5
    persistentvolumeclaims: 2
    requests.storage: "2Gi"

