apiVersion: v1
kind: Pod
metadata:
  name: conf-sec-pod1
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    envFrom:
    - configMapRef:
        name: k8s-env
    - secretRef:
        name: web-db-secret

