apiVersion: v1
kind: Pod
metadata:
  name: conf-sec-pod2
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    env:
    - name: K8S_ENV
      valueFrom:
        configMapKeyRef:
          name: k8s-env-cm
          key: k8s-env-cm.txt
    - name: WEB_DB_CONN
      valueFrom:
        secretKeyRef:
          name: web-db-sec
          key: web-db-sec.txt

