apiVersion: v1
kind: Pod
metadata:
  name: web-db-secret-pod1
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    envFrom:
    - secretRef:
        name: web-db-secret

