apiVersion: v1
kind: Pod
metadata:
  name: web-db-secret-pod3
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    env:
    - name: ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: web-db-secret
          key: rootpw
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: web-db-secret
          key: database

