apiVersion: v1
kind: Pod
metadata:
  name: web-db-secret-pod2
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    volumeMounts:
    - name: web-db-sec
      mountPath: /secrets
  volumes:
  - name: web-db-sec
    secret:
      secretName: web-db-secret

