apiVersion: v1
kind: Pod
metadata:
  name: mysql57-pod
  labels:
    type: mysql57
spec:
  containers:
  - name: mysql57-container
    image: mysql:5.7
    ports:
    - containerPort: 3306 
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "k8spass#"
 
